language:
  ruby

rvm:
  - '1.8.7'
  - '1.9.3'
  - '2.0.0'
  - '2.1.1'
  - jruby-19mode
  - rbx-2.1.1
script:
  bundle exec rspec 
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y r-base r-base-dev
